"""create messages table

Revision ID: 6df9355ccf41
Revises: d7e4c5956f43
Create Date: 2026-07-21 22:05:26.884260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df9355ccf41'
down_revision: Union[str, Sequence[str], None] = 'd7e4c5956f43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create messages after conversations so the foreign key can be established.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_db_schema.conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_db_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop dependent messages before rolling back the conversation-table migration.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages', schema='agent_db_schema')
    # ### end Alembic commands ###
