"""create conversation document model

Revision ID: ca18f9a30f8f
Revises: 6f5745cca683
Create Date: 2026-07-22 22:20:15.476482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca18f9a30f8f'
down_revision: Union[str, Sequence[str], None] = '6f5745cca683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add the join table after both parent tables exist.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_documents',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_db_schema.conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['agent_db_schema.documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'document_id'),
    schema='agent_db_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Remove the join table before either parent-table migration is rolled back.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_documents', schema='agent_db_schema')
    # ### end Alembic commands ###
