"""create conversations table

Revision ID: d7e4c5956f43
Revises: 
Create Date: 2026-07-21 21:36:54.422522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e4c5956f43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the root table that messages will reference.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_db_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Remove the conversations table when rolling this initial migration back.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversations', schema='agent_db_schema')
    # ### end Alembic commands ###
